### ISSUE TITLE
paranoid control

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-desktop#257]
the collision probability of the drop url must be controllable to comply with the android featureset

**Comment by julianseeger** [comment]
cite from @audax 
>We could also just set it to the highest setting (short dropurl) and remove the feature from android. I don't think it has any benefit to have it user controllable.

**Comment by julianseeger** [comment]
According to https://github.com/Qabel/qabel.github.io/issues/163 we currently don't even know how to implement it right. This ticket would only be GUI + creating the background stuff to be able to control the collision probability ... but without the TBD `range` it wouldn't actually change anything

**Comment by roeslpa** [comment]
The GUI is independent from the `range` because the `range` is a constant in the core (see [here](https://github.com/Qabel/qabel-core/blob/master/src/main/java/de/qabel/core/drop/DropIdGenerator.java#L11)). You can implement the GUI without knowing the result of https://github.com/Qabel/qabel.github.io/issues/163 .

Besides the benefit is the following: an enterprise normally does not want the employees to be anonymous and the traffic to be low. Some users who only want a secure channel (confidentiality, integrity, authenticity) but do not want their mobile traffic to be spent on one day might desire the same properties. But some users (activists, whistle blowers, ...) might use Qabel as an anonymity tool and accept the higher traffic. Since all these use cases should be covered by Qabel, this option is not something like the check box of the legal terms.. Please ask @cburkert and @schulze for more details.

**Comment by julianseeger** [comment]
I don't argue about the need of controlling the collision probability.
What I'm arguing about is implementing a feature that lets the user assume that there are collisions in drop urls when there (currently) aren't.

Probably I just misued the term `range` if that equals the size of the dynamic part in the drop url. If I understand this correctly, the important part to control is not the size but the entropy / collision probability and this is defined via the `AdjustableDropIdGenerator` and it's range seems to be defined [here](https://github.com/Qabel/qabel-android/blob/fe20e61ce0b5b1f9c20c555a03f3260c036ae79a/qabelbox/src/main/java/de/qabel/qabelbox/activities/CreateIdentityActivity.java#L140) in the android client
`(getIdentityDropBitsProgress() + 1) * 64`

If I'm right, it would be sufficient to lower this value to increase the collision probability (so even if the dropUrl remains the current size, the **used range** could be shortened), decreasing the entropy, increasing the collision probability to > 0.

So maybe it would be best to move this calculation to the core and just pass in an anonymity level. Then the subprojects don't have to care about this and call like `generateDropId(0.5)` without the need of knowledge about.

... anyways, imho either should this feature not be implemented until the actual dropId calculation formula (however you might call it) is known or the calculation should be moved to the core so that this feature can be implemented without the need to implement a *wrong* formula ...

**Comment by roeslpa** [comment]
I see.. I am in favour of shifting the calculation to the core which can be called as you proposed, since it should be the same for all clients.
Then actual implementation in the core can be modified depending on the result of https://github.com/Qabel/qabel.github.io/issues/163

**Comment by mr-gosh** [comment]
Mockup for Paranoia-Level-Selector during Identity Creation:
![id-creation-wizard-3](https://cloud.githubusercontent.com/assets/3028703/15214406/27471c00-184d-11e6-9612-4444eb3bc56a.png)

**Comment by audax** [comment]
That feature was removed from Android until we find a good use for it. The length of drop IDs was not a good use. @jmt85
