### ISSUE TITLE
Better communication of BETA state of the App

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-desktop#266]
Something like a nice and shiny "BETA" tag somewhere :)

@mr-gosh please think about a good place for that. Keep in mind that it would help if it's implementation is less time consuming ;) Talk to @julianseeger if you need an estimate.

This should be considered important -- let's ship this fix with one of the next hotfix updates if possible.

**Comment by mr-gosh** [comment]
![beta-badge_512](https://cloud.githubusercontent.com/assets/3028703/13741822/96bbbd8c-e9d8-11e5-9b96-794bffaad80e.png)
easiest possible solution would be something like this...?!?

**Comment by thechauffeur** [comment]
I like purple. Let's ship this with an hotfix update.

**Comment by dannywerner** [comment]
pls add with transparent bg, maybe as svg

**Comment by mr-gosh** [comment]
![github-beta-badge](https://cloud.githubusercontent.com/assets/3028703/13746686/c305c47a-e9f4-11e5-95ee-a010bca16ad7.png)

**Comment by julianseeger** [comment]
The last one (with fork me...) doesn't work well with the current desktop client, because it overlaps the controls of the details pane (short message dialog for example). Aligning it to the top right is no option either because it would overlap the avatar too much. So I'll take the purple one for the `0.5.0-beta.1`

**Comment by julianseeger** [comment]
![beta-badge](https://cloud.githubusercontent.com/assets/3258762/13774199/062338a6-ea9e-11e5-9a4e-8c19df329ab0.png)
