### ISSUE TITLE
Check for compatibility with file change merges by hash

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-desktop#417]
https://github.com/Qabel/qabel-core/issues/492

For for eventual problems in combination with the file sync.

**Comment by audax** [comment]
@julianseeger can you give me a hint where I should put such a test? Is there an integration test were 2 sync daemons are running?

**Comment by audax** [comment]
I currently play around with it manually by having multiple syncs with the same remote folder but different local folders which are a subset of eachother. No problems so far, no conflicts.

**Comment by audax** [comment]
Since I couldn't find an error, I'll close this. No automatic test because I couldn't find an error that I would reproduce in a test case.

**Comment by julianseeger** [comment]
Two sync dirs with the same file(s). Both start a sync ... what happens?
I would expect both syncs to upload all files because that hash stuff was afaik only implemented on DM level. To fix that (if the problem exists), one would have to calculate the filehashes before uploading them.

So this ticket would be about: "We know that the problem is now fixed / implemented on a DM level. Is it also fixed on higher levels like a sync / fileupload?

**Comment by audax** [comment]
The files were uploaded because the hash is calculated on upload, but after the files were uploaded, no conflicts occured and the freshly uploaded file was deleted from the block server.

Calculating the hash before the file upload to speed this up and save traffic for the user is an optimization that we should strongly consider in the future, esp. because it shouldn't be that hard to do.
